repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    - id: check-added-large-files
      args: ['--maxkb=500']
    - id: detect-aws-credentials
    - id: check-ast
